### ISSUE TITLE
support parameters for launched programs

### ISSUE THREAD

**Issue by hbinkle** [cascadium/wsl-windows-toolbar-launcher#27]
support passing parameters like in case of meld, two parameters for the two file paths

**Comment by fquinner** [comment]
If you're passing arguments from the command line, I'd expect it's as convenient to just use the command line rather than these shortcuts (as I suspect you would on Linux anyway).

Can you talk me through your workflow here or let me know when you'd usually expect these parameters to work? I can see that the meld desktop file uses the `%F` pattern that we currently throw away because we can't really use it from the windows shortcut and even if we did, I'm not sure how it could come into play (there's no real opportunity to add parameters while clicking on the shortcut).

**Comment by hbinkle** [comment]
right, clicking on the shortcut will not provide any parameters.
My idea was to use that meld batch file for the merge too call in windows git too.
But I guess you're right, it's too specific, It should create my own bat and sh file for this purpose.
