### ISSUE TITLE
Update README.md to calculate 'Win Host IP Addr' without /etc/resolv.conf (for DISPLAY env variable)

### ISSUE THREAD

**Issue by ryeleo** [cascadium/wsl-windows-toolbar-launcher#42]
I recently had to update my `/etc/resolv.conf` to include a proper DNS server -- this resolved an issue I was struggling with in my Network. This had the unfortunate result of breaking my DISPLAY environment variable for wsl-windows-toolbar!

I recommend updating the README.md to include the following example for calculating own IP Address. I think this should work well for *all* wsl folks -- I've only tested on my WSL2 Ubuntu 20.04 so far:

```
export DISPLAY=$(ip route show | grep 'via.*eth0' | cut -d' ' -f3):0.0
```

I hope this is a more resilient solution for folks, but I'm unsure if it is a *stable* alternative to using /etc/resolv.conf. What do you think?

**Comment by terminalstderr** [comment]
Unfortunately, that prior solution I posted is getting the WSL/ubuntu host IP address in the virtual network -- not the Windows host IP address, which is what I need.

I'm still trying to figure out a good solution for my problem here -- suggestions are welcomed!

References:
* [wsl-host.ps1 script](https://gist.github.com/vilic/0edcb3bec10339a3b633bc9305faa8b5) uses the same methodology as in the wsl-windows-toolbar README.md

**Comment by fquinner** [comment]
I think we're actually fine without this because the example provided was only really an example. I have seen literally hundreds of commands to do this, each of which have their pros and cons (for example, your example assumes grep=egrep but that's not the case for all distros). I think what we have is probably fine as a starting point under the assumption that mileage may vary depending on the distro / wsl configuration / customization.
