### ISSUE TITLE
how could Win11 right click toolbar?

### ISSUE THREAD

**Issue by virginity-is-cool** [cascadium/wsl-windows-toolbar-launcher#46]

**Comment by fquinner** [comment]
Great question - unfortunately this is not possible in Windows 11 since they neutered the taskbar (generally). I did test when the windows 10 insiders build had full wslg support, but the windows 11 taskbar is unrecognizable from that build.

But as of Windows 11, this script is not actually required. If you run [powertoys](https://github.com/microsoft/PowerToys), you can enable Powertoys Run and use alt+space. Your GUI apps from your WSL installs will have shortcuts there with your distribution name in brackets, e,g.:

![image](https://user-images.githubusercontent.com/8431703/142381404-ae81ccc4-d646-46f8-aa61-0c274163d4e6.png)

Note you may wait for the Windows indexer to refresh after you install a new app, but it will get there eventually automatically.

They will also appear in your start menu if you prefer not to run powertoys run (but powertoys run reminds me of ulauncher which is my go-to launcher on Linux anyway so I feel at home there :) )

**Comment by fquinner** [comment]
Updated the readme to reflect this.

**Comment by fquinner** [comment]
See latest version - installs to start menu, will get package together in coming days for pypi:

1a4394ae454808a70f41922c22c824b1bdd22b51
